// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GyroCam",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "GyroCam",
            targets: ["AppModule"],
            displayVersion: "0.15",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To record video"),
                .motion(purposeString: "To use gyro data in videos"),
                .microphone(purposeString: "To make videos with sound"),
                .photoLibrary(purposeString: "To save recorded videos"),
                .locationAlwaysAndWhenInUse(purposeString: "To record camera location metadata")
            ],
            appCategory: .photography
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
