name: iOS Canary Build

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: macos-latest  # macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      # - name: Install CocoaPods
      #   run: |
      #     gem install cocoapods
      #     cd Xcode
      #     pod install --repo-update

      - name: Get MARKETING_VERSION and CURRENT_PROJECT_VERSION
        id: version_info
        run: |
          export MARKETING_VERSION=$(xcodebuild -showBuildSettings -project Xcode/GyroCam.xcodeproj | grep MARKETING_VERSION | sed 's/[ ]*MARKETING_VERSION = //')
          export CURRENT_PROJECT_VERSION=$(xcodebuild -showBuildSettings -project Xcode/GyroCam.xcodeproj | grep CURRENT_PROJECT_VERSION | sed 's/[ ]*CURRENT_PROJECT_VERSION = //')
          echo "MARKETING_VERSION=$MARKETING_VERSION" >> $GITHUB_ENV
          echo "CURRENT_PROJECT_VERSION=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV

      - name: Increment build number
        run: |
          NEW_BUILD_NUMBER=$((CURRENT_PROJECT_VERSION+1))
          /usr/libexec/PlistBuddy -c "Set :CURRENT_PROJECT_VERSION $NEW_BUILD_NUMBER" Xcode/GyroCam.xcodeproj/project.pbxproj
          echo "Updated build number to $NEW_BUILD_NUMBER"

      - name: Build iOS app
        run: |
          xcodebuild -workspace Xcode/GyroCam.xcworkspace \
            -scheme GyroCam \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/GyroCam.xcarchive archive

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/GyroCam.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist Xcode/ExportOptions.plist  # Ensure you have an export plist

      - name: Create Payload directory
        run: mkdir -p Payload

      - name: Move app into Payload directory
        run: mv build/GyroCam.app Payload/

      - name: Create .ipa file
        run: |
          cd Payload
          zip -r9 ../GyroCam.ipa ./*
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: GyroCam.ipa
          tag_name: v${{ env.CURRENT_PROJECT_VERSION }}  # Use the build number as the release tag
          name: GyroCam v${{ env.MARKETING_VERSION }} (Build ${{ env.CURRENT_PROJECT_VERSION }})  # Use version and build number in release title
          body: |
            GyroCam build ${{ env.CURRENT_PROJECT_VERSION }} is now available.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
